'use client';

import React, { useState } from 'react';
import { generateId } from '@/lib/utils';
import { AtlasItem, ItemType, PrimaryCategory } from '@/types/atlas';

import {
  X,
  Link2,
  FileText,
  Camera,
  Mic,
  FileCode2,
  Sparkles,
  Upload,
  CheckCircle2,
  Loader2,
} from 'lucide-react';

interface QuickCaptureModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSaveItem: (item: AtlasItem) => void;
}

export function QuickCaptureModal({
  isOpen,
  onClose,
  onSaveItem,
}: QuickCaptureModalProps) {
  const [activeTab, setActiveTab] = useState<'url' | 'note' | 'file' | 'voice' | 'code'>('url');
  const [url, setUrl] = useState('');
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [isRecording, setIsRecording] = useState(false);
  const [recordingTime, setRecordingTime] = useState(0);
  const [errorMsg, setErrorMsg] = useState('');

  if (!isOpen) return null;

  const handleProcessAndSave = async () => {
    setErrorMsg('');
    setIsAnalyzing(true);

    try {
      let finalContent = content;
      let detectedType: ItemType = 'link';

      if (activeTab === 'url') {
        detectedType = url.includes('youtube.com') || url.includes('youtu.be') ? 'video' : 'article';
      } else if (activeTab === 'note') {
        detectedType = 'note';
      } else if (activeTab === 'code') {
        detectedType = 'code';
      } else if (activeTab === 'voice') {
        detectedType = 'voice';
      }

      // Call Gemini Analyze Server API
      const res = await fetch('/api/ai/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          url: activeTab === 'url' ? url : undefined,
          title: title || undefined,
          content: finalContent || (activeTab === 'url' ? `Saved link from ${url}` : 'Quick saved note'),
          type: detectedType,
        }),
      });

      const data = await res.json();

      let aiResult = data.data || {};

      const newItem: AtlasItem = {
        id: generateId('item'),
        title: aiResult.title || title || (url ? new URL(url).hostname : 'Saved Item'),
        type: (aiResult.type as ItemType) || detectedType,
        url: url || undefined,
        domain: url ? new URL(url).hostname : undefined,
        content: finalContent || aiResult.summary || 'No text body captured.',
        summary: aiResult.summary || 'Summary auto-generated by GoAtlas AI.',
        keyTakeaways: aiResult.keyTakeaways || ['Captured in Universal Inbox'],
        category: (aiResult.category as PrimaryCategory) || 'General',
        tags: aiResult.tags || ['saved', activeTab],
        keywords: aiResult.keywords || [],
        relatedTopics: aiResult.relatedTopics || [],
        collectionIds: [],
        readingTimeMinutes: aiResult.readingTimeMinutes || 3,
        readingProgress: 0,
        isFavorite: false,
        isArchived: false,
        isRead: false,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        visitCount: 1,
        author: 'Saved Content',
      };

      onSaveItem(newItem);
      resetForm();
      onClose();
    } catch (err: any) {
      console.error('Error during AI Quick Capture:', err);
      // Fallback save if API network error
      const fallbackItem: AtlasItem = {
        id: generateId('item'),
        title: title || (url ? new URL(url).hostname : 'Saved Item'),


        type: activeTab === 'url' ? 'link' : activeTab === 'code' ? 'code' : 'note',
        url: url || undefined,
        domain: url ? new URL(url).hostname : undefined,
        content: content || url || 'Content',
        summary: title ? `Note titled ${title}` : 'Quick saved item.',
        keyTakeaways: ['Saved locally to GoAtlas inbox.'],
        category: 'General',
        tags: [activeTab, 'saved'],
        keywords: [],
        relatedTopics: [],
        collectionIds: [],
        readingTimeMinutes: 2,
        readingProgress: 0,
        isFavorite: false,
        isArchived: false,
        isRead: false,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        visitCount: 1,
      };
      onSaveItem(fallbackItem);
      resetForm();
      onClose();
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setTitle(file.name);
    const reader = new FileReader();

    if (file.type.startsWith('image/')) {
      reader.onload = async (event) => {
        const base64 = event.target?.result as string;
        setIsAnalyzing(true);
        try {
          const res = await fetch('/api/ai/ocr', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ base64Data: base64, mimeType: file.type }),
          });
          const ocrRes = await res.json();
          if (ocrRes.data) {
            setTitle(ocrRes.data.title || file.name);
            setContent(ocrRes.data.extractedText || 'Image OCR output');
          }
        } catch {
          setContent(`Uploaded image ${file.name}`);
        } finally {
          setIsAnalyzing(false);
        }
      };
      reader.readAsDataURL(file);
    } else {
      reader.onload = (event) => {
        setContent((event.target?.result as string) || `File: ${file.name}`);
      };
      reader.readAsText(file);
    }
  };

  const resetForm = () => {
    setUrl('');
    setTitle('');
    setContent('');
    setIsAnalyzing(false);
    setIsRecording(false);
    setErrorMsg('');
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/40 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-white border border-neutral-200 rounded-2xl w-full max-w-xl shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        {/* Modal Header */}
        <div className="px-6 py-4 border-b border-neutral-100 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-blue-50 text-blue-600 flex items-center justify-center font-bold">
              <Sparkles className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-base font-semibold text-neutral-900">
                Save to GoAtlas
              </h2>
              <p className="text-xs text-neutral-500">
                AI automatically organizes, summarizes, and indexes your content
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-neutral-400 hover:text-neutral-700 hover:bg-neutral-100 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Navigation */}
        <div className="flex border-b border-neutral-100 bg-neutral-50/50 p-1.5 gap-1 text-xs">
          <button
            onClick={() => setActiveTab('url')}
            className={`flex-1 py-2 px-3 rounded-lg font-medium flex items-center justify-center gap-1.5 transition-all ${
              activeTab === 'url'
                ? 'bg-white text-blue-600 shadow-sm border border-neutral-200'
                : 'text-neutral-600 hover:text-neutral-900'
            }`}
          >
            <Link2 className="w-3.5 h-3.5" /> URL / Link
          </button>

          <button
            onClick={() => setActiveTab('note')}
            className={`flex-1 py-2 px-3 rounded-lg font-medium flex items-center justify-center gap-1.5 transition-all ${
              activeTab === 'note'
                ? 'bg-white text-blue-600 shadow-sm border border-neutral-200'
                : 'text-neutral-600 hover:text-neutral-900'
            }`}
          >
            <FileText className="w-3.5 h-3.5" /> Note
          </button>

          <button
            onClick={() => setActiveTab('file')}
            className={`flex-1 py-2 px-3 rounded-lg font-medium flex items-center justify-center gap-1.5 transition-all ${
              activeTab === 'file'
                ? 'bg-white text-blue-600 shadow-sm border border-neutral-200'
                : 'text-neutral-600 hover:text-neutral-900'
            }`}
          >
            <Camera className="w-3.5 h-3.5" /> Screenshot / PDF
          </button>

          <button
            onClick={() => setActiveTab('code')}
            className={`flex-1 py-2 px-3 rounded-lg font-medium flex items-center justify-center gap-1.5 transition-all ${
              activeTab === 'code'
                ? 'bg-white text-blue-600 shadow-sm border border-neutral-200'
                : 'text-neutral-600 hover:text-neutral-900'
            }`}
          >
            <FileCode2 className="w-3.5 h-3.5" /> Code
          </button>

          <button
            onClick={() => setActiveTab('voice')}
            className={`flex-1 py-2 px-3 rounded-lg font-medium flex items-center justify-center gap-1.5 transition-all ${
              activeTab === 'voice'
                ? 'bg-white text-blue-600 shadow-sm border border-neutral-200'
                : 'text-neutral-600 hover:text-neutral-900'
            }`}
          >
            <Mic className="w-3.5 h-3.5" /> Voice
          </button>
        </div>

        {/* Tab Form Contents */}
        <div className="p-6 space-y-4">
          {activeTab === 'url' && (
            <div>
              <label className="block text-xs font-semibold text-neutral-700 mb-1">
                Paste Web URL, YouTube video, GitHub, Article or Tweet
              </label>
              <input
                type="url"
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                placeholder="https://example.com/article"
                className="w-full px-3.5 py-2.5 text-sm bg-neutral-50 border border-neutral-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:bg-white transition-all font-mono"
              />
            </div>
          )}

          {activeTab === 'file' && (
            <div>
              <label className="block text-xs font-semibold text-neutral-700 mb-1">
                Upload Screenshot (OCR) or PDF / Document
              </label>
              <div className="border-2 border-dashed border-neutral-200 rounded-xl p-6 text-center hover:border-blue-400 transition-colors bg-neutral-50/50">
                <Upload className="w-8 h-8 text-neutral-400 mx-auto mb-2" />
                <p className="text-xs text-neutral-600 mb-1">
                  Drag & drop image, PDF, or text file here
                </p>
                <input
                  type="file"
                  accept="image/*,application/pdf,text/*"
                  onChange={handleFileUpload}
                  className="hidden"
                  id="file-upload-input"
                />
                <label
                  htmlFor="file-upload-input"
                  className="inline-block px-3 py-1.5 bg-white border border-neutral-300 rounded-lg text-xs font-medium text-neutral-700 hover:bg-neutral-50 cursor-pointer shadow-sm"
                >
                  Browse Computer
                </label>
              </div>
            </div>
          )}

          {activeTab === 'voice' && (
            <div className="text-center py-4 bg-neutral-50 border border-neutral-200 rounded-xl">
              <Mic className="w-10 h-10 text-red-500 mx-auto mb-2 animate-pulse" />
              <p className="text-sm font-semibold text-neutral-800">
                Voice Note Capture
              </p>
              <p className="text-xs text-neutral-500 mb-3">
                Speak your idea or thought. AI will clean up and transcribe automatically.
              </p>
              <textarea
                value={content}
                onChange={(e) => setContent(e.target.value)}
                placeholder="Type or paste audio transcription here..."
                className="w-full h-24 px-3 py-2 text-xs bg-white border border-neutral-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-500"
              />
            </div>
          )}

          {(activeTab === 'note' || activeTab === 'code') && (
            <div>
              <label className="block text-xs font-semibold text-neutral-700 mb-1">
                Optional Title
              </label>
              <input
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="Title or topic..."
                className="w-full px-3.5 py-2 text-sm bg-neutral-50 border border-neutral-200 rounded-xl mb-3 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:bg-white"
              />

              <label className="block text-xs font-semibold text-neutral-700 mb-1">
                {activeTab === 'code' ? 'Code Snippet' : 'Note Content / Markdown'}
              </label>
              <textarea
                value={content}
                onChange={(e) => setContent(e.target.value)}
                rows={5}
                placeholder={
                  activeTab === 'code'
                    ? '// Paste TypeScript, Rust, Python code snippet...'
                    : 'Write notes, ideas, insights...'
                }
                className="w-full px-3.5 py-2.5 text-sm bg-neutral-50 border border-neutral-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:bg-white font-mono"
              />
            </div>
          )}

          {errorMsg && (
            <p className="text-xs text-red-600 bg-red-50 p-2 rounded-lg">{errorMsg}</p>
          )}
        </div>

        {/* Modal Footer */}
        <div className="px-6 py-4 bg-neutral-50 border-t border-neutral-100 flex items-center justify-between">
          <span className="text-xs text-neutral-500 flex items-center gap-1">
            <Sparkles className="w-3.5 h-3.5 text-blue-600" />
            Automatic Gemini AI Tagging & Synthesis
          </span>

          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="px-4 py-2 text-xs font-medium text-neutral-600 hover:text-neutral-900 hover:bg-neutral-200/50 rounded-xl transition-colors"
            >
              Cancel
            </button>

            <button
              onClick={handleProcessAndSave}
              disabled={isAnalyzing || (!url && !content && !title)}
              className="px-5 py-2 text-xs font-medium bg-blue-600 hover:bg-blue-700 text-white rounded-xl shadow-sm disabled:opacity-50 transition-all flex items-center gap-2"
            >
              {isAnalyzing ? (
                <>
                  <Loader2 className="w-3.5 h-3.5 animate-spin" />
                  Analyzing with AI...
                </>
              ) : (
                <>
                  <CheckCircle2 className="w-3.5 h-3.5" />
                  Save to Atlas
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
